---
deployment:
  tasks:
    - /bin/bash -lc '
        set -e;
        REPO="/home/painclin/repositories/Tehran-Aesthetics";
        SRC_THEME="$REPO/app/public/wp-content/themes/tehran-aesthetics-child";
        SRC_PLUGINS="$REPO/app/public/wp-content/plugins";
        DOCROOT="/home/painclin/public_html/ta";
        DEST_THEME="$DOCROOT/wp-content/themes/tehran-aesthetics-child";
        DEST_PLUGINS="$DOCROOT/wp-content/plugins";

        echo "== Ensure target folders ==";
        /bin/mkdir -p "$DEST_THEME" "$DEST_PLUGINS";

        echo "== Copy THEME (clean replace) ==";
        /bin/rm -rf "$DEST_THEME";
        /bin/mkdir -p "$DEST_THEME";
        /bin/cp -a "$SRC_THEME/." "$DEST_THEME/";

        echo "== Copy PLUGINS (merge, per plugin) ==";
        if [ -d "$SRC_PLUGINS" ]; then
          for P in "$SRC_PLUGINS"/*; do
            [ -e "$P" ] || continue;
            BN="$(/usr/bin/basename "$P")";
            /bin/rm -rf "$DEST_PLUGINS/$BN";
            /bin/cp -a "$P" "$DEST_PLUGINS/";
          done
        else
          echo "No plugins directory in repo (skip)";
        fi;

        /bin/date > "$DEST_THEME/DEPLOY_OK.txt";
        echo "== DONE (Tehran-Aesthetics) ==";
      '
