---
deployment:
  tasks:
    # مقصد وردپرس تهران-استتیکس (دایرکتوری نصب WP)
    - export DEPLOYPATH=/home/painclin/public_html/ta/

    # ساخت پوشه‌ها (اگر نبود)
    - /bin/mkdir -p $DEPLOYPATH/wp-content/themes/tehran-aesthetics-child/
    - /bin/mkdir -p $DEPLOYPATH/wp-content/plugins/

    # دیپلوی تم
    - /bin/rsync -av --delete --exclude=".git*" --exclude=".cpanel.yml" \
      ./wp-content/themes/tehran-aesthetics-child/ \
      $DEPLOYPATH/wp-content/themes/tehran-aesthetics-child/

    # (اختیاری) دیپلوی پلاگین‌های اختصاصی همین ریپو
    - /bin/rsync -av --delete --exclude=".git*" --exclude=".cpanel.yml" \
      ./wp-content/plugins/ \
      $DEPLOYPATH/wp-content/plugins/

    # هرگز هسته وردپرس، wp-config.php یا uploads را از ریپو overwrite نکن
